export { default as authRoutes } from "./authRoutes.js";
export { default as categoryRoutes } from "./categoryRoutes.js";
export { default as productRoutes } from "./productRoutes.js";
export { default as cartRoutes } from "./cartRoutes.js";
export { default as orderRoutes } from "./orderRoutes.js";
export { default as feedbackRoutes } from "./feedbackRoutes.js";
export { default as userRoutes } from "./userRoutes.js";
export { default as wishlistRoutes } from "./wishlistRoutes.js";
export { default as adminRoutes } from "./adminRoutes.js";
